### PR TITLE
Fixing the logging package names in the unit test projects.

### PR DESCRIPTION
**Pull request by Praburaj**

### CODE REVIEW

**Comment by Praburaj** [comment]
@victorhurdugaci @Eilon @ianhong

**Comment by davidfowl** [comment]
:shipit:

**Comment by victorhurdugaci** [comment]
Looks good. But we should make the CI fail first by cleaning those network shares that have old packages.

**Comment by Praburaj** [comment]
>But we should make the CI fail first by cleaning those network shares that have old packages.

Yeah.

**Pull request merged**
