### PR TITLE
added missing reference to System.Data.Entity which causes build to fail.

### PR DESCRIPTION
**Pull request by redwards510**
The line UseGlobalApplicationHostFile just added itself after I built, so I assume that's ok.

### CODE REVIEW

**Comment by Eilon** [comment]
Does this happen in the `dev` branch? That's the most current branch. The `master` branch here is for `beta7` so I want to make sure there isn't a mismatch here.

**Comment by redwards510** [comment]
I haven't tried the dev branch. I just cloned the repository so I could try playing around with this project and it fails to build because of the missing reference.

**Comment by Eilon** [comment]
@kichalla canyou take a look to see if `master` is broken?

**Comment by kichalla** [comment]
@Eilon based on the PR change, its a change in `MvcMusicStore.csproj`, so our builds would not pick it up?

**Comment by ajcvickers** [comment]
@Eilon Are you sure this is something we want to do? System.Data.Entity is the namespace from legacy versions of EF. Unless something has changed I don't think we want MusicStore to reference this.

**Comment by Eilon** [comment]
@ajcvickers it's the MvcMusicStore project (the original one using .NET 4.x) that was using EF, so I think in principal that's fine. However, we just deleted MvcMusicStore from the `dev` branch so I'm not sure it's worth fixing something that we just deleted. All we kept in `dev` was the ASP.NET 5 / EF 7 version of MusicStore.

Nevertheless, I'm curious how we didn't notice that it was broken...

But given all that, I suspect it's fine to close this PR.

**Comment by ajcvickers** [comment]
@Eilon Okay, that makes sense.

**Comment by Eilon** [comment]
Closing this because in 1 week this won't matter (we deleted the affected project).

**Pull request closed without merging**
