### PR TITLE
Set log level.

### PR DESCRIPTION
**Pull request by tony-xia**
Set correct log level for WebHost

### CODE REVIEW

**Comment by Eilon** [comment]
@BrennanConroy can you review & merge?

**Comment by BrennanConroy** [comment]
You should be using SetMinimumLevel in this scenario
________________________________

**Comment by tony-xia** [comment]
Updated, using SetMinimumLevel().

**Comment by BrennanConroy** [comment]
Thanks for the PR! Looks good @tony-xia

**Pull request merged**
