### PR TITLE
Moved IConfiguration in Startup.cs

### PR DESCRIPTION
**Pull request by heathyates**
Created PR request here at instructions of @Praburaj and @Eilon from PR #406. As @Eilon stated [here](https://github.com/aspnet/MusicStore/pull/406#discussion_r25559797). We have the following pattern: 
1.Fields
2.Constructors
3.Properties
4.Events (which we almost never have these days)
5.Methods
6.Nested types
First, I agree with this pattern and follow the pattern above in most cases. 

My very small and humble request is to consider the special case of methods with accessors to be placed below fields for better readability. This is a practice that is popular and well established. I know this is a very minor and humble PR request, but I hope you will consider it. Being able to read fields and accessors at the beginning of a class does more for me than documentation to describe what I could expect in a class. Much like reading the index/contents page of a book or intro for a chapter. 

At the very least, I humbly thank you for your hard work and efforts. I am a super fan your team and the new approach Microsoft has taken by interacting with community developers here. Thank you.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@heathyates__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by heathyates** [comment]
As additional evidence to support this change. Today I found this tutorial from Taiseer which also demonstrates putting IConfiguration at the [top](http://bitoftech.net/2014/11/18/getting-started-asp-net-5-mvc-6-web-api-entity-framework-7/).

**Comment by victorhurdugaci** [comment]
Is this PR still needed?

**Comment by heathyates** [comment]
@victorhurdugaci It's still valid, so to speak. If you agree with the sentiment, I can make a new PR for the beta4 version of music store. Let me know how you feel about it.

**Comment by kichalla** [comment]
Closing this as what we currently have is just fine.

**Pull request closed without merging**
