### PR TITLE
Use proper JavaScript comment. Closes #519

### LINKED ISSUE #519: Inline JavaScript code with C# Razor comments
The main example ships with syntax error due to using Razor comment syntax in inline JS script tag in main template:
https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Views/Shared/_Layout.cshtml#L28
```razor
<script>
        @*To display what\'s new in the store*@
        $(function () {
            $.connection.hub.logging = true;
            var announcementsHub = $.connection.Announcement;
```
It could work in VS, but breaks my Atom editor. 
Thanks!

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit replaces Razor syntax specific comment with default,
line JavaScript comment

I've already signed CLA!

Thanks!

### CODE REVIEW

**Comment by dougbu** [comment]
@peterblazejewicz does Atom handle Razor comments any better if they appear outside `<script>` elements?

**Comment by peterblazejewicz** [comment]
@dougbu Yes, as expected:

**Comment by Eilon** [comment]
:shipit: This change is fine, even though it is functionally slightly different from what it was.

**Comment by Eilon** [comment]
@dougbu can you merge and watch the CI?

**Comment by kichalla** [comment]
I already merged this actually.

**Comment by Eilon** [comment]
Oh... then close :smile:

**Comment by kichalla** [comment]
Sure! commit 49b96a7f2f8557face72cf8bd20fadae41145500

**Pull request closed without merging**
