### PR TITLE
React to configuration #197

### PR DESCRIPTION
**Pull request by kirthik**
@kichalla , @suhasj

### CODE REVIEW

**Comment by kichalla** [comment]
:shipit:

**Comment by suhasj** [comment]
@kirthik can you check the SPA app as well to see if that needs this change ?

**Comment by kirthik** [comment]
@suhasj I checked for all calls of `GetSubKey` in MusicStore repo and updated all of them. SPA app is not calling `GetSubKey`

**Comment by suhasj** [comment]
:shipit:

**Comment by kichalla** [comment]
54ddefe88c2c8d80009b191dea81407083610b12

**Pull request closed without merging**
