### PR TITLE
Remove unused `using Microsoft.AspNet.Diagnostics.Entity`

### PR DESCRIPTION
**Pull request by dougbu**
- also sort `using`s

### CODE REVIEW

**Comment by dougbu** [comment]
@Eilon could you make `dev` the default branch in this repo please? Took an extra click to create this amazing PR.

**Comment by Eilon** [comment]
@dougbu :shipit: to get it in, then I'll change the branch.

**Comment by dougbu** [comment]
a02b003

**Comment by Eilon** [comment]
Default branch updated.

**Pull request closed without merging**
