### PR TITLE
Updated Identity to 2.0 and made changes for UserManager instantiation

### PR DESCRIPTION
**Pull request by suhasj**
Updated Identity to 2.0
Added UserManager factory method
registered UserManager for CreatePerOwinContext
Updated AccountController
Merged ApplicationDbContext to MusicStoreEntities
Updated complexity of the password in web.config

cc @Praburaj @HaoK @rustd

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Is this PR still needed?

**Comment by HaoK** [comment]
Ask @rustd

**Comment by rustd** [comment]
Yeah. The mvc5 music store should match the latest Mvc5 template

**Comment by suhasj** [comment]
Need to verify if there have been anymore updates to the templates since this PR

**Comment by davidfowl** [comment]
This can't be important

**Pull request closed without merging**
