### PR TITLE
Re-enable the Ntlm authentication tests

### PR DESCRIPTION
**Pull request by Praburaj**
User.IsSignedIn() does not return true for NTLM. So pulling the NTLM check out of the code block.

### CODE REVIEW

**Comment by Praburaj** [comment]
@HaoK

**Comment by Praburaj** [comment]
@HaoK - can we extend `User.IsSignedIn()` to return `true` for `WindowsIdentity` as well?

**Comment by HaoK** [comment]
@blowdart What do you think?  I added a new ClaimsPrincipal extension for Identity, currently it only looks for identities generated by Identity, I'm not sure it makes sense to couple WindowsIdentity logic to identity, as typically you wouldn't want to pull in Identity just to use the extension method...

**Comment by blowdart** [comment]
Yea, it feels weird to extend it to a WindowsIdentity

**Pull request merged**
