### PR TITLE
Include Microsoft.AspNetCore.Diagnostics in MusicStore

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
:shipit: if it fixes the build

**Comment by ryanbrandenburg** [comment]
@JunTaoLuo local repro indicates it will.

**Comment by JunTaoLuo** [comment]
:+1:

**Comment by Eilon** [comment]
Oops, I broke this, sorry! And thanks for fixing!

**Pull request merged**
