### PR TITLE
Unified naming

### PR DESCRIPTION
**Pull request by Jeffiy**
Unified naming of DefaultAdminPassword

### CODE REVIEW

**Comment by Eilon** [comment]
Is there a purpose to changing this? I think the current password is fine, no?

**Comment by Jeffiy** [comment]
Yeah, it works well, but I think unified the name of DefaultAdminUserName and DefaultAdminPassword would be better, thanks.

**Comment by Eilon** [comment]
I agree it looks a bit nicer if it's consistent.

@kichalla can you merge?

**Comment by kichalla** [comment]
26e33b9d68670e3eefed7d4c233f93bf163bd9ea

**Pull request closed without merging**
