### PR TITLE
fix casing bug

### PR DESCRIPTION
**Pull request by friism**
the dir name is lower-case

### CODE REVIEW

**Comment by Praburaj** [comment]
Could you send the PR to the dev branch?

**Comment by friism** [comment]
@Praburaj the dev branch is fubar because the script stuff is commented out: https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore.Spa/project.json#L44

... I don't really know why that is.

**Comment by victorhurdugaci** [comment]
Is this PR still needed?

**Comment by friism** [comment]
@victorhurdugaci well, it's still wrong so I'd say yes. I haven't tested recently to see some part of the the system makes paths case-insensitive, but I doubt it.

**Comment by Eilon** [comment]
@friism BTW there's an updated CLA here that needs to be signed: https://cla2.dotnetfoundation.org/ - it's even simpler than the old form.

**Comment by friism** [comment]
@Eilon seriously... I spent several months getting my masters to approve the old one.

**Comment by Eilon** [comment]
@friism yeah unfortunately we changed the projects last week from MS Open Tech to .NET Foundation to unify all the OSS projects under one umbrella. The new CLA form requires a signature only from you, though it asks that you have permission from your employer (if applicable). Hopefully this one will be easier for you to swing.

**Comment by friism** [comment]
@Eilon On it.

**Comment by Eilon** [comment]
Thanks!

**Comment by davidfowl** [comment]
Is this still relevant?

**Comment by kichalla** [comment]
I made this change myself as CLA hasn't been signed for this PR. Thanks @friism

**Comment by friism** [comment]
@kichalla understood, thanks

**Pull request closed without merging**
