### PR TITLE
react to removal of PlatformAbstractions

### PR DESCRIPTION
**Pull request by anurse**
This PR removes all references to PlatformAbstractions.

Part of aspnet/PlatformAbstractions#50

### CODE REVIEW

**Comment by natemcmaster** [comment]
FYI Microsoft.DotNet.PlatformAbstractions is actually different from Microsoft.Extensions.PlatformAbstractions, but looks like any code using this was removed by @kichalla  in https://github.com/aspnet/MusicStore/pull/774. So :shipit:

**Comment by BrennanConroy** [comment]
Remove `DotNetPlatformAbstractionsVersion` from props file?

**Comment by Eilon** [comment]
Please check CI failures

**Comment by anurse** [comment]
@natemcmaster Yep, I went through and cleaned those up in a few places while I was cleaning up the other PlatformAbstractions :).

**Pull request merged**
