### PR TITLE
remove duplicity " glyphicon "

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
removing duplicate information

### CODE REVIEW

**Comment by Eilon** [comment]
@kichalla can you review and merge?

**Comment by kichalla** [comment]
@ralmsdeveloper Did you delete the branch? I am unable to find it in your fork

**Comment by Eilon** [comment]
@kichalla can you somehow pull it directly from the pull request branch at https://github.com/aspnet/MusicStore/pull/628/commits/f3b65e2d1af00b202ec40b0a2e25c8092c10fb50?

Or just re-do the change manually...

**Comment by kichalla** [comment]
95eaa0a11c5bb5d43d342169cf81d6c91a07c843

**Pull request closed without merging**
