### PR TITLE
Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
Prepping to be merged once ready.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@NTaylorMullen__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Taylor Mullen). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by Praburaj** [comment]
Should `kre` be changed to `dnx` in any of these places? 

https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L177
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L316
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L68
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L168
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L310
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L271
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L275
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L194
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L194
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L271
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/DeploymentUtility.cs#L275

**Comment by NTaylorMullen** [comment]
@Praburaj yes it should, i'll update this PR and my update script

**Comment by NTaylorMullen** [comment]
@Praburaj I've updated the PR, pleas ensure that I've covered all places you were concerned with.

**Comment by muratg** [comment]
Looks good.  :shipit:

**Comment by Praburaj** [comment]
:shipit:

**Pull request merged**
