### PR TITLE
add ShoppingCart table style

### PR DESCRIPTION
**Pull request by Jeffiy**

### CODE REVIEW

**Comment by Eilon** [comment]
@Jeffiy any chance you could show before/after screenshots of this?

**Comment by Jeffiy** [comment]
Oops, I can not upload any images. you can see the changes [here](http://runjs.cn/detail/3dcuk2do)

**Comment by Eilon** [comment]
@Jeffiy sorry, that site loads very slowly for me and then the image itself doesn't load at all. Can you upload here in GitHub? There's a link at the bottom of the comment textbox that allows you to select images to upload.

**Comment by Eilon** [comment]
Nevermind, it finally loaded:
untitled

**Comment by Eilon** [comment]
Seems pretty nice to me. @kichalla can you review and merge?

**Comment by Jeffiy** [comment]
I can't upload any images probably because of the GFW.

**Comment by kichalla** [comment]
8d18e1beac231f4292f6e44412eda5189de45fd6

This looks nice. Thanks @Jeffiy

**Pull request closed without merging**
