### PR TITLE
Support using PostgreSQL as a database (via Npgsql)

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
Fixes https://github.com/aspnet/MusicStore/issues/710

**Comment by tmds** [comment]
Can I get some feedback on the PR?

**Comment by Hussain-arif** [comment]
feedback of what type ??????

**Comment by tmds** [comment]
> feedback of what type ??????
Code review to get the PR merged.

**Comment by tmds** [comment]
@Tratcher can you or someone else have a look please?

**Comment by Eilon** [comment]
@tmds thanks for sending the PR, however for the time being the MusicStore app here is really just a test app that we use for our end-to-end test automation. As such, we generally don't add anything that won't be used by our automated tests because it increases the cost of maintaining this app.

If you'd like to maintain a separate copy of MusicStore in your own repo that is modified to show alternative options, such as using PostgreSQL, we would be happy to have a link from the readme of this repo to point to that.

**Pull request closed without merging**
