### PR TITLE
Broken Links in Header after logging

### PR DESCRIPTION
**Pull request by kirst**
Added asp-area to Components, _Layout and _LoginPartial links (Header links are broken in Admin area #666 )

### CODE REVIEW

**Comment by Eilon** [comment]
Seems pretty straightforward, so :shipit: from me. @kichalla ?

**Comment by kirst** [comment]
This would also correct #680

**Comment by Eilon** [comment]
@kirst indeed, it appears so, thanks!

**Comment by kichalla** [comment]
1bce0acfde5b9fe5e5e48b6311bdfb232cdbf444

Thanks! @kirst

**Pull request closed without merging**
